name: CI
on:
  pull_request:
  push:
    tags-ignore: [ '**' ]
    branches: [ '**' ]
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2
      - name: Test
        run: |
          make test
      - name: Image Build
        run: |
          ./scripts/image.sh
        env:
          TAG: dev
          REGISTRY: 'docker.io'
          REPO: 'hxstarrys'
